# lib/awale/BUILD

cc_library(
    name = "cmds_lib",
    srcs = glob(["**/*.c"]),
    hdrs = glob(["**/*.h"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib/valuable:valuable_lib",
    ],
)