# lib/awale/BUILD

cc_library(
    name = "client_lib",
    srcs = glob(["*.c"]),
    hdrs = glob(["*.h"]),
    visibility = ["//visibility:public"],
    deps = [
        "//lib/socket:socket_lib",
    ],
)