#ifndef CMD_H
#define CMD_H

enum CMD {
  CMD_USER_INFO = 0x00,
  CMD_USER_LOGIN = 0x01,
  CMD_USER_LOGOUT = 0x02,

  CMD_USER_LIST_ALL = 0x03,
  CMD_USER_LIST_FRIENDS = 0x04,

  CMD_USER_ADD_FRIEND = 0x05,
  CMD_USER_REMOVE_FRIEND = 0x06,

  CMD_CHALLENGE = 0x07, // commander pour défier un joueur
  CMD_CHALLENGE_HANDLE = 0x08,

  CMD_GAME_PLAY = 0x09, // commande pour jouer un coup
  CMD_GAME_LEAVE = 0x0A,

  CMD_GAME_LIST = 0x0B,
  CMD_GAME_STATE = 0x0C,

  CMD_GAME_OBSERVE = 0x0D,

  CMD_CHAT_WRITE = 0x0E,

  CMD_GAME_STATE_EVENT = 0x0F,

  CMD_ERROR = 0xFF,
};

#endif